export const environment = {
  production: true,
  apiUrl: 'https://api.spotify.com/v1',
  currentUser: 'me',
  playlists: 'playlists',
  tracks: 'tracks',
  recommendations: 'recommendations',
  browse: 'browse',
  categories: 'categories',
  artist: 'artists',
  search: 'search',
  player: 'player',
  albums: 'albums',
  users: 'users',
  country: 'BR',
  locale: 'pt_BR',

  clientId: '3a17febb99344e8180c6cf30378d09d8',
  redirectUri: 'https://spotify-manager-lucasluan01.vercel.app/',
  authEndPoint: 'https://accounts.spotify.com/authorize',
  scopes: [
    'playlist-modify-private',
    'playlist-modify-public',
    'playlist-read-private',
    'user-library-read',
    'user-read-email',
    'user-read-private',
    'user-read-recently-played',
  ]
};
